trigger:
  branches:
    include:
      - main  # Trigger the pipeline when changes are made to main 

pool:
  vmImage: 'ubuntu-latest'

variables:
# defined in Azure DevOps variables
  variables:
  DOCKER_USERNAME: $(dockerUsername)
  DOCKER_PASSWORD: $(dockerPassword)
  BACKEND_IMAGE_NAME: 'django-backend'
  FRONTEND_IMAGE_NAME: 'react-frontend'
  TAG: 'latest'

steps:
# Login to Docker Hub
- task: Docker@2
  displayName: 'Login to docker hub'
  inputs:
    command: 'login'
    containerRegistry: 'Docker Hub'
    username: '$(DOCKER_USERNAME)'
    password: '$(DOCKER_PASSWORD)'

# Build and push the backend image
- task: Docker@2
  displayName: 'Build and push the backend image'
  inputs:
    containerRegistry: 'Docker Hub'
    repository: '$(DOCKER_USERNAME)/$(BACKEND_IMAGE_NAME)'
    command: 'buildAndPush'
    Dockerfile: '$(Build.SourcesDirectory)/Computex/Dockerfile' 
    tags: '$(TAG)'

# Build and push the frontend image
- task: Docker@2
  displayName: 'Build and push the frontend image'
  inputs:
    containerRegistry: 'Docker Hub'
    repository: '$(DOCKER_USERNAME)/$(FRONTEND_IMAGE_NAME)'
    command: 'buildAndPush'
    Dockerfile: '$(Build.SourcesDirectory)/ComputexFrontend/Dockerfile' 
    tags: '$(TAG)'

# Step 2: Deploy to Azure Web App for Containers
# - task: AzureWebAppContainer@2
#   displayName: 'Deploy to Azure Web App for Containers'
#   inputs:
#     azureSubscription: '<your-service-connection>'  # Name of the Azure service connection
#     appName: '<your-webapp-name>'  # Name of your Azure Web App
#     imageName: '$(ACR_NAME).azurecr.io/$(IMAGE_NAME):$(IMAGE_TAG)'
