version: 0.2

phases:
  install:
    commands:
      - echo "Updating yum and installing HashiCorp repo..."
      - yum install -y yum-utils
      - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - yum -y install terraform
      - terraform -version

  build:
    commands:
      - echo "Running Terraform in terraform/aws"
      - aws ssm get-parameter --name "private_key" --with-decryption --region eu-north-1 --query "Parameter.Value" --output text > terraform/aws/key_path
      - chmod 600 terraform/aws/key_path
      - cd terraform/aws
      - terraform init
      - terraform apply -auto-approve

artifacts:
  files:
    - '**/*'
