version: 0.2

phases:
  install:
    commands:
      - echo Installing Terraform...
      - curl -LO https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip
      - unzip -o terraform_1.6.6_linux_amd64.zip
      - mv terraform /usr/local/bin/
  build:
    commands:
      - cd terraform/aws
      - terraform init
      - terraform apply -auto-approve
